# Generated by Django 4.1.5 on 2023-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
